security:
    encoders:
        Nerick\PortfolioBundle\User:
            id: Nerick.PortfolioBundle.Encoder
        FOS\UserBundle\Model\UserInterface:
            id: Nerick.PortfolioBundle.Encoder
#    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    user:
                        password: pwd4user
                        roles: 'ROLE_USER'
                    admin:
                        password: pwd4admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
#            pattern: ^/
            anonymous: ~
#            form_login:
#                failure_handler: Nerick.PortfolioBundle.AuthenticationRestHandler
#                success_handler: Nerick.PortfolioBundle.AuthenticationRestHandler
            logout: true
#    access_control:
#        - { path: ^/api/admin/test$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/admin/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/admin/login.*$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/api/admin, roles: [ ROLE_ADMIN ] }
        
#    access_control:
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }